spring.application.name=EstudosSpringRest

spring.server.port=${server_port:8080}

## DB - ZEUS
spring.datasource.url = jdbc:postgresql://${host}:${port}/zeus
spring.datasource.username=${usuario}
spring.datasource.password=${senha}

spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database.POSTGRESQL=org.hibernate.dialect.PostgreSQL10Dialect

## SPRING DOC
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# Server Context Path
server.servlet.context-path=/estudos