spring.application.name=EstudosSpringRest

spring.profiles.active=${profile:dev}
spring.server.port=${server_port}

## DB - ZEUS
spring.datasource.url = jdbc:postgresql://${host}:${port}/zeus
spring.datasource.username=${usuario}
spring.datasource.password=${senha}

#spring.jpa.database-plataform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database.POSTGRESQL=org.hibernate.dialect.PostgreSQL10Dialect

api.security.token.secret=${JWT_SECRET}

## SPRING DOC
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.show-common-extensions=true