spring.application.name=EstudosSpringRest
server.port=8081

## DB - ZEUS
spring.datasource.url=jdbc:postgresql://localhost:5432/zeus
spring.datasource.username= ${usuario}
spring.datasource.password= ${senha}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database.POSTGRESQL=org.hibernate.dialect.PostgreSQL10Dialect